server.port=8081

spring.datasource.url=jdbc:h2:file:./data/quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
logging.level.org.springframework.web=DEBUG
spring.security.user.name=shivani
spring.security.user.password=shivani@123

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

jwt.secret=${JWT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile